# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-29 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhukkad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
